### ISSUE TITLE
Grayscale image causes TypeError

### ISSUE THREAD

**Issue by jinsu** [hhatto/smartcrop.py#2]
When an image is in grayscale mode, the pixel values are integer type and not a tuple.

for example,
running smartcrop on `http://aff.bstatic.com/images/hotel/max500/583/58362651.jpg` image throws an error.

```
Traceback (most recent call last):
  File "smartcrop.py", line 341, in <module>
    main()
  File "smartcrop.py", line 328, in main
    ret = sc.crop(img, crop_options)
  File "smartcrop.py", line 100, in crop
    result = self.analyse(image)
  File "smartcrop.py", line 128, in analyse
    _output = self.detect_edge(image, _output)
  File "smartcrop.py", line 187, in detect_edge
    lightness = sample(_id[p])
  File "smartcrop.py", line 54, in sample
    return cie(_id[0], _id[1], _id[2])
TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by hhatto** [comment]
fix in 3af68e9e31110bf2700b1c416f7a681c90d1c2cf

Thanks.
